name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Modify this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
  Push:
    runs-on: ubuntu-latest      
    
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Use the current directory as the build context
        push: true
        tags: kunalbhat55/python:3.11.6-alpine
  
